### ISSUE TITLE
can't parse json array on iOS

### ISSUE THREAD

**Issue by newebug** [NetEase/pomelo-unityclient-socket#10]
We have a handler return json data like this:

{
  serverList: [{'a':'some ip'}, {'b': 'an other ip'}]
}

It works fine on Android and HTML, but on iOS will get error and can't get correct data, anybody resolved this problem? or any idea?

Please help, we have work so long on a pomelo game project.

**Comment by koalaylj** [comment]
simplejson has a bug about parsing list on ios,you can use array instead of List<xxx> 。

**Comment by newebug** [comment]
Thank you.
