### ISSUE TITLE
bug of HeartBeatService

### ISSUE THREAD

**Issue by dontbmh** [NetEase/pomelo-unityclient-socket#17]
Hi,

I'm new to client-server sort of things and quite not sure if it's a bug or that's what you intend to do.

For HeartBeatService.cs, the timeout is set to interval*2, but the real timeout happened at interval * 3, coz the timeout is adding up(HeartBeatService.cs line 37~38) below the timeout checking.

Any suggestion? Thanks in advance.

**Comment by koalaylj** [comment]
`timeout` will be reset to 0(resetTimeout() function) when message arrived.`timeout` is the interval between two adjacent heartbeat.`timeout += (int)span.TotalMilliseconds;`will calculate it.


it's just interval * 2.

**Comment by dontbmh** [comment]
Hi,


let's assume that resetTimeout is never called from the beginning of the heartbeat service.


Would the disconnect be called at approximately at interval * 3?


------------------
Cheers.


Best regards,


Dirk.
 

 




------------------ Original ------------------

**Comment by koalaylj** [comment]
Oops! it's a bug. you're right.

we should use `timeout = (int)span.TotalMilliseconds`
instead of`timeout +=(int)span.TotalMilliseconds`.

thank you!

**Comment by dontbmh** [comment]
Hi,


I really thought  timeout = (int)span.TotalMilliseconds should be put above timeout checking.‍


I mean that put line 37,38 above the if condition check.


------------------
Cheers.


Best regards,


Dirk.
 

 




------------------ Original ------------------

**Comment by koalaylj** [comment]
It makes sense.
