### ISSUE TITLE
源代码中握手部分疑惑

### ISSUE THREAD

**Issue by foodyi** [NetEase/pomelo-unityclient-socket#24]
internal void start (JsonObject user, Action<JsonObject> callback)
        {

```
        this.transporter.start ();
        this.handshake.request (user, callback);
        this.state = ProtocolState.handshaking;
    }
```

为什么要调用transporter.start,里面方法直接就是接受数据，但是之前没有并没有send数据啊，而数据长度为0还要断开连接，安全搞不懂了。
现在和pomelo握手没有数据返回

**Comment by zk-luke** [comment]
`PomeloClient.initClient`的时候 socket已经初始化好了，`transporter.start()`才开始监听网络回传数据。
socket先监听网络数据通信后再send才能接收到网络返回的数据，回忆下socket通信流程。
监听网络数据后，`this.handshake.request(user, callback)`这句才开始send握手信息。
返回0那么处理的原因可参考[MSDN Socket.EndReceive](https://msdn.microsoft.com/zh-cn/library/w7wtt64b%28v=vs.110%29.aspx)
握手没数据这个并不是这个原因导致的。
