### ISSUE TITLE
To use the dotnetClient, just include ./dist/*.dll in your project.这句话考虑到Android和iPhone的感受了么

### ISSUE THREAD

**Issue by SteveCruise** [NetEase/pomelo-unityclient-socket#38]

**Comment by zk-luke** [comment]
使用unity开发么？直接dll放unity项目里面就好了啊。

**Comment by SteveCruise** [comment]
@koalaylj what？它用的simpleJson是dll库，这也能在Android上运行？我用的是unity
https://github.com/NetEase/pomelo-unityclient-socket/tree/master/lib
